home_page: home.md # filepath under /source/
menu_page: menu.md # filepath under /source/
author_img: # filepath of author image
favicon_url: favicon.png # filepath of favicon
favicon_svg: # html tag like svg, example: <svg class="icon logo" aria-hidden="true"><use xlink:href="#icon-kaifa"></use></svg>

zoom_image: true
codeblock:
  # Code Highlight theme
  # Available values: normal | night | night eighties | night blue | night bright | solarized | solarized dark | galactic
  highlight_theme: normal

comments:
  utterances:
    enable: false
    user: # your github user name
    repo: # your github repo name
    theme: github-light # github-light | github-dark | github-dark-orange | icy-dark | dark-blue | photon-dark
  disqus:
    enable: false
    shortname: # your disqus shortname
  gitalk:
    enable: false
    githubID: # your github id
    repo: # GitHub repository e.g. kaiiiz.github.io
    ClientID: # GitHub Application Client ID
    ClientSecret: # GitHub Application Client Secret
    adminUser: # GitHub repository owner and collaborators
    labels: "gitalk" # GitHub issue labels
    distractionFreeMode: true

# Google Analytics
# https://analytics.google.com/analytics/web/
google_analytics: # UA-XXXXX-Y

# Google Adsense (谷歌广告)
google_adsense:
  enable: true
  auto_ads: true
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client: ca-pub-xxxxxxx
  enable_page_level_ads: true

ad: # 手动广告代码
  post_top: # post顶部
  post_bottom: # post底部
  skip_top: # 不要顶部广告的页面
    - index.html
    - xxx.html
  skip_bottom: # 不要底部广告的页面
    - xxx.html

skip_post_info: # 不要post_info的页面

# Inject
# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
# 插入代码到头部 </head> 之前 和 底部 </body> 之前
inject:
  head:
    # - <link rel="stylesheet" href="/xxx.css">
  bottom:
    # - <script src="xxxx"></script>

